#!/bin/bash

set -Eeux

WDIR=$1
ARCH=$2
WM=$3

case $ARCH in
  win32) WINETEST=$WDIR/local/lib/wine/i386-windows/winetest.exe;;
  win64) WINETEST=$WDIR/local/lib/wine/x86_64-windows/winetest.exe;;
esac

export DISPLAY=:0
export LC_ALL=C.UTF-8
export PATH="$WDIR/local/bin:$PATH"

export WINEARCH=$ARCH
export WINEPREFIX=$HOME/$ARCH
export WINEDEBUG=err-all,fixme-all

echo > $HOME/xorg.conf
echo 'Section "Device"' >> $HOME/xorg.conf
echo '  Identifier "dummy"' >> $HOME/xorg.conf
echo '  Driver "dummy"' >> $HOME/xorg.conf
echo '  VideoRam 32768' >> $HOME/xorg.conf
echo 'EndSection' >> $HOME/xorg.conf

case $WM in
  fvwm)     echo "exec /usr/bin/fvwm -f config -c \"Style * MwmDecor\" -c \"Style * UsePPosition\" 2>/dev/null" >$HOME/.xinitrc;;
  i3)       echo "exec /usr/bin/i3 2>/dev/null" >$HOME/.xinitrc;;
  kwin)     echo "exec /usr/bin/kwin_x11 2>/dev/null" >$HOME/.xinitrc;;
  lwm)      echo "exec /usr/bin/lwm 2>/dev/null" >$HOME/.xinitrc;;
  marco)    echo "exec /usr/bin/marco 2>/dev/null" >$HOME/.xinitrc;;
  metacity) echo "exec /usr/bin/metacity 2>/dev/null" >$HOME/.xinitrc;;
  muffin)   echo "exec /usr/bin/muffin 2>/dev/null" >$HOME/.xinitrc;;
  mutter)   echo "exec /usr/bin/mutter --x11 2>/dev/null" >$HOME/.xinitrc;;
  nulldrv)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  desktop)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  openbox)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  xfwm4)    echo "exec /usr/bin/xfwm4 2>/dev/null" >$HOME/.xinitrc;;
  xmonad)   echo "exec /usr/bin/xmonad 2>/dev/null" >$HOME/.xinitrc;;
esac
env -C $HOME startx -- -config xorg.conf $DISPLAY & sleep 1

xrandr --addmode default 1024x768
xrandr --output default --mode 1024x768
xrandr

pulseaudio --start --exit-idle-time=-1

case $WM in
  fvwm)     DRIVER=x11;  WM=$DRIVER-$WM;;
  i3)       DRIVER=x11;  WM=$DRIVER-$WM;;
  kwin)     DRIVER=x11;  WM=$DRIVER-$WM;;
  lwm)      DRIVER=x11;  WM=$DRIVER-$WM;;
  marco)    DRIVER=x11;  WM=$DRIVER-$WM;;
  metacity) DRIVER=x11;  WM=$DRIVER-$WM;;
  muffin)   DRIVER=x11;  WM=$DRIVER-$WM;;
  mutter)   DRIVER=x11;  WM=$DRIVER-$WM;;
  openbox)  DRIVER=x11;  WM=$DRIVER-$WM;;
  xfwm4)    DRIVER=x11;  WM=$DRIVER-$WM;;
  xmonad)   DRIVER=x11;  WM=$DRIVER-$WM;;
  desktop)  DRIVER=x11;  WM=$DRIVER-$WM; wine reg add "HKCU\\Software\\Wine\\Explorer\\Desktops" /v "Default" /d "800x600" /f;;
  nulldrv)  DRIVER=null;;
esac
wine reg add "HKCU\\Software\\Wine\\Drivers" /v "Graphics" /d "$DRIVER" /f
wine reg add "HKCU\\Software\\Wine\\WineDbg" /v "ShowCrashDialog" /t REG_DWORD /d 0 /f
wine reg add "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AeDebug" /v "Auto" /t REG_DWORD /d 1 /f
wineserver -w

wine $WINETEST -q -t rbernon-$WM-$ARCH \
  -m "Rémi Bernon <rbernon@codeweavers.com>" ||:
