#!/bin/bash

set -Eeux

WDIR=$1
ARCH=$2
TEST=$3
EVENT=$4

# do not submit these wm
case $TEST in
  i3)       EVENT=push;;
  lwm)      EVENT=push;;
  marco)    EVENT=push;;
  metacity) EVENT=push;;
  muffin)   EVENT=push;;
  xfwm4)    EVENT=push;;
  xmonad)   EVENT=push;;
esac

case $ARCH in
  win32) WINETEST=$WDIR/local/lib/wine/i386-windows/winetest.exe;;
  wow64) WINETEST=$WDIR/local/lib/wine/i386-windows/winetest.exe; WINEARCH=win64;;
  win64) WINETEST=$WDIR/local/lib/wine/x86_64-windows/winetest.exe;;
esac

export DISPLAY=:0
export LC_ALL=C.UTF-8
export PATH="$WDIR/local/bin:$PATH"
export XDG_RUNTIME_DIR=$(mkdir -p $HOME/.run && chmod 700 $HOME/.run && echo $HOME/.run)

export WINE=wine
export WINEARCH=${WINEARCH:-$ARCH}
export WINEPREFIX=$HOME/$ARCH
export WINEDEBUG=err-all,fixme-all

echo > $HOME/xorg.conf
echo 'Section "Device"' >> $HOME/xorg.conf
echo '  Identifier "dummy"' >> $HOME/xorg.conf
echo '  Driver "dummy"' >> $HOME/xorg.conf
echo '  VideoRam 32768' >> $HOME/xorg.conf
echo 'EndSection' >> $HOME/xorg.conf

case $TEST in
  fvwm)     echo "exec /usr/bin/fvwm -f config -c \"Style * MwmDecor\" -c \"Style * UsePPosition\" 2>/dev/null" >$HOME/.xinitrc;;
  modeset)  echo "exec /usr/bin/fvwm -f config -c \"Style * MwmDecor\" -c \"Style * UsePPosition\" 2>/dev/null" >$HOME/.xinitrc;;
  i3)       echo "exec /usr/bin/i3 2>/dev/null" >$HOME/.xinitrc;;
  kwin)     echo "exec /usr/bin/kwin_x11 2>/dev/null" >$HOME/.xinitrc;;
  lwm)      echo "exec /usr/bin/lwm 2>/dev/null" >$HOME/.xinitrc;;
  marco)    echo "exec /usr/bin/marco 2>/dev/null" >$HOME/.xinitrc;;
  metacity) echo "exec /usr/bin/metacity 2>/dev/null" >$HOME/.xinitrc;;
  muffin)   echo "exec /usr/bin/muffin 2>/dev/null" >$HOME/.xinitrc;;
  mutter)   echo "exec /usr/bin/mutter --x11 2>/dev/null" >$HOME/.xinitrc;;
  nulldrv)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  desktop)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  openbox)  echo "exec /usr/bin/openbox 2>/dev/null" >$HOME/.xinitrc;;
  xfwm4)    echo "exec /usr/bin/xfwm4 2>/dev/null" >$HOME/.xinitrc;;
  xmonad)   echo "exec /usr/bin/xmonad 2>/dev/null" >$HOME/.xinitrc;;
  wayland)  echo "" >$HOME/.xinitrc;;
  vulkan)   echo "exec /usr/bin/fvwm -f config -c \"Style * MwmDecor\" -c \"Style * UsePPosition\" 2>/dev/null" >$HOME/.xinitrc;;
esac

. /etc/os-release
INFO="Docker running $PRETTY_NAME / $(uname -a), "
INFO="$INFO[CPU:$(nproc)*$(lscpu|grep "Model name:"|cut -d: -f2-|xargs echo)"
INFO="$INFO RAM:$(grep "MemTotal:" /proc/meminfo|cut -d: -f2-|tr -d ' ') display:dummy"
case $TEST in
  fvwm)     INFO="$INFO $(/usr/bin/fvwm --version|head -1)";;
  modeset)  INFO="$INFO with emulated modesetting";;
  i3)       INFO="$INFO $(/usr/bin/i3 --version|head -1)";;
  kwin)     INFO="$INFO $(/usr/bin/kwin_x11 --version|head -1)";;
  lwm)      INFO="$INFO $(/usr/bin/lwm --version|head -1)";;
  marco)    INFO="$INFO $(/usr/bin/marco --version|head -1)";;
  metacity) INFO="$INFO $(/usr/bin/metacity --version|head -1)";;
  muffin)   INFO="$INFO $(/usr/bin/muffin --version|head -1)";;
  mutter)   INFO="$INFO $(/usr/bin/mutter --version|head -1)";;
  openbox)  INFO="$INFO $(/usr/bin/openbox --version|head -1)";;
  xfwm4)    INFO="$INFO $(/usr/bin/xfwm4 --version|head -1)";;
  xmonad)   INFO="$INFO $(/usr/bin/xmonad --version|head -1)";;
  nulldrv)  INFO="$INFO with nulldrv driver";;
  desktop)  INFO="$INFO with virtual desktop";;
  wayland)  INFO="$INFO $(/usr/bin/weston --version|head -1) (headless)";;
  vulkan)   INFO="$INFO with vulkan Direct3D Renderer";;
esac
INFO="$INFO]"

case $TEST in
  fvwm)     DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  modeset)
    $WINE reg add "HKCU\\Software\\Wine\\X11 Driver" /v "EmulateModeset" /d "Y" /f
    DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  i3)       DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  kwin)     DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  lwm)      DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  marco)    DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  metacity) DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  muffin)   DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  mutter)
    $WINE reg add "HKCU\\Software\\Wine\\X11 Driver" /v "Decorated" /d "N" /f
    DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  openbox)  DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  xfwm4)    DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  xmonad)   DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  desktop)  DRIVER=x11; RENDERER=gl;  TEST=$DRIVER-$TEST;;
  nulldrv)  DRIVER=null; RENDERER=gl;;
  wayland)  DRIVER=wayland; RENDERER=gl; TEST=$DRIVER;;
  vulkan)   DRIVER=x11; RENDERER=vulkan; TEST=$RENDERER;;
esac

case $DRIVER in
  x11)
    env -C $HOME startx -- -config xorg.conf $DISPLAY & while ! xprop -root _NET_SUPPORTING_WM_CHECK | grep -q 'window id'; do sleep 1; done
    xrandr --addmode DUMMY0 1024x768
    xrandr --output DUMMY0 --mode 1024x768
    xrandr
    ;;
  wayland)
    weston --backend=headless-backend.so & sleep 1
    export WAYLAND_DISPLAY="$(find $XDG_RUNTIME_DIR/wayland-[0-9] -printf %f)"
    ;;
  null)
    ;;
esac

pulseaudio --start --exit-idle-time=-1

$WINE reg add "HKCU\\Software\\Wine\\Drivers" /v "Graphics" /d "$DRIVER" /f
$WINE reg add "HKCU\\Software\\Wine\\Direct3D" /v "Renderer" /d "$RENDERER" /f
$WINE reg add "HKCU\\Software\\Wine\\WineDbg" /v "ShowCrashDialog" /t REG_DWORD /d 0 /f
$WINE reg add "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AeDebug" /v "Auto" /t REG_DWORD /d 1 /f
case $TEST in
  *-desktop) $WINE reg add "HKCU\\Software\\Wine\\Explorer\\Desktops" /v "Default" /d "800x600" /f;;
esac
wineserver -kw

$WINE $WINETEST -q -o $TEST-$ARCH.report -t rbernon-$TEST-$ARCH -i "$INFO" \
  -m "Rémi Bernon <rbernon@codeweavers.com>" ||:

case $EVENT in
  push) echo curl 'https://test.winehq.org/submit' -X POST -F reportfile=@$TEST-$ARCH.report -F submit="Upload File";;
  *) curl 'https://test.winehq.org/submit' -X POST -F reportfile=@$TEST-$ARCH.report -F submit="Upload File" ||:;;
esac
