name: build
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:stable
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: .ccache
          key:
            cache-linux-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            cache-linux-${{ matrix.arch }}

      - name: Build
        run: |
          $PWD/build-linux ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}
          path: usr

  test-linux:
    needs: [build-linux]
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:stable
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]
        test: [nulldrv, desktop, fvwm, openbox, kwin, mutter, wayland, vulkan]
        include:
          - arch: wow64
            test: fvwm
          - arch: wow64
            test: vulkan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        if: ${{ matrix.arch == 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-win64

      - name: Download
        if: ${{ matrix.arch != 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          useradd github && mkdir -p /home/github /home/github/Documents /home/github/Desktop && chown github:github -R /home/github
          su - github $PWD/test-linux $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ github.event_name }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-linux-${{ matrix.test }}-${{ matrix.arch }}.report
          path: /home/github/*.report

  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        arch: [win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: .ccache
          key:
            cache-macos-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            cache-macos-${{ matrix.arch }}

      - name: Build
        run: |
          $PWD/build-macos ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-${{ matrix.arch }}
          path: usr

  test-macos:
    needs: [build-macos]
    runs-on: macos-13
    strategy:
      matrix:
        arch: [win64]
        test: [opengl, vulkan]
        include:
          - arch: wow64
            test: opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ github.event_name }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: macos-*.report

  test-macos-m1ros2:
    needs: [build-macos]
    runs-on: macos-14
    strategy:
      matrix:
        arch: [win64, wow64]
        test: [m1ros2-vulkan]
        include:
          - arch: wow64
            test: m1ros2-opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Test
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          eval "$(/usr/local/bin/brew shellenv)"
          arch -x86_64 brew install --overwrite python

          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          arch -x86_64 $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ github.event_name }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: m1ros2-*.report

  clean:
    needs: [test-linux, test-macos, test-macos-m1ros2]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
